# Form implementation generated from reading ui file 'EmulatorFileManager2.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1336, 334)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label_EmulatorFileManager = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Label_EmulatorFileManager.setMaximumSize(QtCore.QSize(50000, 32))
        self.Label_EmulatorFileManager.setLineWrapColumnOrWidth(0)
        self.Label_EmulatorFileManager.setObjectName("Label_EmulatorFileManager")
        self.verticalLayout_3.addWidget(self.Label_EmulatorFileManager)
        self.Button_FindEmulators = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_FindEmulators.setObjectName("Button_FindEmulators")
        self.verticalLayout_3.addWidget(self.Button_FindEmulators)
        self.VFileLayout = QtWidgets.QVBoxLayout()
        self.VFileLayout.setObjectName("VFileLayout")
        self.ds_layout = QtWidgets.QHBoxLayout()
        self.ds_layout.setObjectName("ds_layout")
        self.Three_ds = QtWidgets.QLabel(parent=self.centralwidget)
        self.Three_ds.setMinimumSize(QtCore.QSize(64, 32))
        self.Three_ds.setScaledContents(False)
        self.Three_ds.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Three_ds.setObjectName("Three_ds")
        self.ds_layout.addWidget(self.Three_ds)
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.ds_layout.addWidget(self.label_16)
        self.ExeLocation_FileDialogue_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExeLocation_FileDialogue_2.setObjectName("ExeLocation_FileDialogue_2")
        self.ds_layout.addWidget(self.ExeLocation_FileDialogue_2)
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.ds_layout.addWidget(self.label_17)
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.ds_layout.addWidget(self.pushButton_25)
        self.pushButton_38 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_38.setObjectName("pushButton_38")
        self.ds_layout.addWidget(self.pushButton_38)
        self.VFileLayout.addLayout(self.ds_layout)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(64, 32))
        self.label_22.setScaledContents(False)
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.ExeLocation_FileDialogue_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExeLocation_FileDialogue_4.setObjectName("ExeLocation_FileDialogue_4")
        self.horizontalLayout_19.addWidget(self.ExeLocation_FileDialogue_4)
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.pushButton_41 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_19.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_19.addWidget(self.pushButton_42)
        self.VFileLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setMinimumSize(QtCore.QSize(64, 32))
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.ExeLocation_FileDialogue_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExeLocation_FileDialogue_3.setObjectName("ExeLocation_FileDialogue_3")
        self.horizontalLayout_18.addWidget(self.ExeLocation_FileDialogue_3)
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.pushButton_39 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_18.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_18.addWidget(self.pushButton_40)
        self.VFileLayout.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addLayout(self.VFileLayout)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 32))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.FileExtractorLayout = QtWidgets.QHBoxLayout()
        self.FileExtractorLayout.setObjectName("FileExtractorLayout")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textBrowser.setObjectName("textBrowser")
        self.FileExtractorLayout.addWidget(self.textBrowser)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.FileExtractorLayout.addWidget(self.pushButton_4)
        self.textBrowser_9 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_9.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.FileExtractorLayout.addWidget(self.textBrowser_9)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.FileExtractorLayout.addWidget(self.pushButton_2)
        self.EmulatorDropBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.EmulatorDropBox.setObjectName("EmulatorDropBox")
        self.EmulatorDropBox.addItem("")
        self.EmulatorDropBox.addItem("")
        self.FileExtractorLayout.addWidget(self.EmulatorDropBox)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.FileExtractorLayout.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.FileExtractorLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1336, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_EmulatorFileManager.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Emulator File Manager</p></body></html>"))
        self.Button_FindEmulators.setText(_translate("MainWindow", "Find Emulators"))
        self.Three_ds.setText(_translate("MainWindow", "3DS:"))
        self.label_16.setText(_translate("MainWindow", "EXE Location"))
        self.ExeLocation_FileDialogue_2.setText(_translate("MainWindow", "C://"))
        self.label_17.setText(_translate("MainWindow", "Game Folder"))
        self.pushButton_25.setText(_translate("MainWindow", "C://"))
        self.pushButton_38.setText(_translate("MainWindow", "Launch"))
        self.label_22.setText(_translate("MainWindow", "PS1:"))
        self.label_23.setText(_translate("MainWindow", "EXE Location"))
        self.ExeLocation_FileDialogue_4.setText(_translate("MainWindow", "C://"))
        self.label_24.setText(_translate("MainWindow", "Game Folder"))
        self.pushButton_41.setText(_translate("MainWindow", "C://"))
        self.pushButton_42.setText(_translate("MainWindow", "Launch"))
        self.label_21.setText(_translate("MainWindow", "PS2:"))
        self.label_18.setText(_translate("MainWindow", "EXE Location"))
        self.ExeLocation_FileDialogue_3.setText(_translate("MainWindow", "C://"))
        self.label_19.setText(_translate("MainWindow", "Game Folder"))
        self.pushButton_39.setText(_translate("MainWindow", "C://"))
        self.pushButton_40.setText(_translate("MainWindow", "Launch"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zip Location</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "C://"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select Emulator </p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "C://"))
        self.EmulatorDropBox.setItemText(0, _translate("MainWindow", "Emulator 1"))
        self.EmulatorDropBox.setItemText(1, _translate("MainWindow", "Emulator2"))
        self.pushButton_3.setText(_translate("MainWindow", "Extract"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
